language: objective-c
env:
  matrix:
    - FORMULA_VERSION=
    - FORMULA_VERSION=--HEAD
rvm: system
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/openconnect-gui
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/horar/homebrew-openconnect-gui
script:
  - brew install openconnect-gui $FORMULA_VERSION --verbose
  - brew audit openconnect-gui --strict
  - brew test openconnect-gui
matrix:
  fast_finish: true

